### PR TITLE
YETUS-871. cleanup the junit output format

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by aw-was-here** [comment]
> we should change the various CI config files we have that still refer to `--junit-results-xml` in the same PR.

Doh. Good catch.  I'll let it run through all of the CI systems in my fork to see what happens.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-70/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   2m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  yamllint  |   0m  2s |  There were no new yamllint issues.  |
||| _ Other Tests _ |
| :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-70/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/70 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux c397f359a946 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / e8f542b |
| Max. process+thread count | 45 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-70/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
Tested this on a variety of CI systems, all appear to be working as expected.

**Comment by aw-was-here** [comment]
Thanks!

**Pull request merged**
