### PR TITLE
YETUS-894. fix yetus semaphore CI build script

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 152 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 183 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/65 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux bc238967edd2 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / de5900d |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 101 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 1 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 17 | The patch does not generate ASF License warnings. |
| | | 141 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/65 |
| Optional Tests | dupname asflicense shellcheck shelldocs yamllint |
| uname | Linux 046364a92937 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / de5900d |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 0 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 10 | The patch does not generate ASF License warnings. |
| | | 54 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/65 |
| Optional Tests | dupname asflicense shellcheck shelldocs yamllint |
| uname | Linux daf8f4da453b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / de5900d |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-65/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
Thanks!

**Pull request merged**
