### PR TITLE
speed up builds

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 360 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 9 | The patch does not generate ASF License warnings. |
| | | 386 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/42 |
| Optional Tests |  dupname  asflicense  shellcheck  shelldocs  |
| uname | Linux 60af8530470f 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / bf88009 |
| maven | version: Apache Maven 3.3.9 |
| shellcheck | v0.4.6 |
| Max. process+thread count | 23 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/1/console |
| Powered by | Apache Yetus 0.10.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 133 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 4 | Maven dependency ordering for patch |
| +1 | shellcheck | 2 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 15 | The patch does not generate ASF License warnings. |
| | | 185 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/42 |
| Optional Tests |  dupname  asflicense  shellcheck  shelldocs  |
| uname | Linux b6ed2b175f38 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / bf88009 |
| maven | version: Apache Maven 3.3.9 |
| shellcheck | v0.4.6 |
| Max. process+thread count | 52 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/3/console |
| Powered by | Apache Yetus 0.10.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/4/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 28 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 3 | Maven dependency ordering for patch |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 76 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/42 |
| Optional Tests |  dupname  asflicense  shellcheck  shelldocs  |
| uname | Linux c246592c964c 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / bf88009 |
| maven | version: Apache Maven 3.3.9 |
| shellcheck | v0.4.6 |
| Max. process+thread count | 24 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/4/console |
| Powered by | Apache Yetus 0.10.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/6/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 25 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 3 | Maven dependency ordering for patch |
| +1 | shellcheck | 1 | There were no new shellcheck issues. |
| +1 | shelldocs | 1 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 20 | The patch does not generate ASF License warnings. |
| | | 92 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/42 |
| Optional Tests |  dupname  asflicense  shellcheck  shelldocs  |
| uname | Linux 1681c5fdb729 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3db66f6 |
| maven | version: Apache Maven 3.3.9 |
| shellcheck | v0.4.6 |
| Max. process+thread count | 24 (vs. ulimit of 2000) |
| modules | C: . asf-site-src precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/6/console |
| Powered by | Apache Yetus 0.10.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/yetus/pull/42 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/42 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-42/7/console |
| Powered by | Apache Yetus 0.10.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
This got merged.

**Pull request closed without merging**
