### PR TITLE
YETUS-685. add junit xml as a reporting format

### PR DESCRIPTION
**Pull request by aw-was-here**
This is a very simple implementation that likely requires more work.  But it does work for at least Circle CI and Gitlab to some degree.

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1411 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 4 | Maven dependency ordering for patch |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 2 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 15 | The patch does not generate ASF License warnings. |
| | | 1467 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/48 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux f85f8a126103 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0255243 |
| Max. process+thread count | 50 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/2/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1401 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 4 | Maven dependency ordering for patch |
| +1 | shellcheck | 1 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 0 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 16 | The patch does not generate ASF License warnings. |
| | | 1458 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/48 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux 5f4e945df985 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0255243 |
| Max. process+thread count | 51 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/3/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 83 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 4 | Maven dependency ordering for patch |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 2 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 14 | The patch does not generate ASF License warnings. |
| | | 136 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/48 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux 1cdf6b833ac3 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0255243 |
| Max. process+thread count | 51 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/4/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 192 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| -1 | shellcheck | 7 | The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | shelldocs | 2 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 0 | There were no new yamllint issues. |
||| _ Other Tests _ |
| 0 | asflicense | 35 | ASF License check generated no output? |
| | | 319 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/48 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux 4b4b264d5ccb 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0255243 |
| shellcheck | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/4/artifact/out/diff-patch-shellcheck.txt |
| Max. process+thread count | 47 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/4/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
At first I was confused, then I got that this the report of all the yetus tests in the junit result format.

It feels weird for this to be in the junit plugin for some reason? I think because it shouldn't need someone to be relying on any junit testing of their actual source, right?

Also this addition makes it clearer to me that we shouldn't be conflating sources of changes to test with reporting mechanisms (not sure why the html report didn't).

Anywho. That's all stuff not really critical for this first pass.

Maybe too early to include docs? Should atleast make clearer in the cli help that if their project generates its own junit output this isn't going to aggregate it.

+1

**Comment by aw-was-here** [comment]
> It feels weird for this to be in the junit plugin for some reason? I think because it shouldn't need someone to be relying on any junit testing of their actual source, right?

Correct. It was just more of "well, it's junit related so put in the junit.sh file so it is easy to find, I guess?"  We should probably prioritize splitting test-patch.d up. Making robots.d separate has been very nice. haha.

> too early

Yeah.  This patch works on [Circle CI](https://circleci.com/gh/zededa/eve/464) and [Gitlab CI](https://gitlab.com/_a__w_/buretoolbox/merge_requests/5) but I cannot get Jenkins to take in the report. So I'm still trying to get that part working.  I guess we could commit as is and then I could open up another to get Jenkins working with it, clean it up, etc.   Thoughts?

**Comment by aw-was-here** [comment]
... and of course, I just had Jenkins work in my test bed.  Let me clean up this patch and get it committed.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/5/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 124 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 4 | Maven dependency ordering for patch |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | yamllint | 1 | There were no new yamllint issues. |
||| _ Other Tests _ |
| +1 | asflicense | 20 | The patch does not generate ASF License warnings. |
| | | 189 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/48 |
| Optional Tests | dupname asflicense yamllint shellcheck shelldocs |
| uname | Linux e74797c417af 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0255243 |
| Max. process+thread count | 50 (vs. ulimit of 2000) |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/5/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 yamllint=1.12.1 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
[Jenkins test results](https://builds.apache.org/job/yetus-github-multibranch/job/PR-48/5/testReport/(root)/)

WOOT!

**Comment by aw-was-here** [comment]
Thanks for the review!

**Pull request merged**
