### PR TITLE
YETUS-739. yetus' mvn site fails when run with built-in dockerfile

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by aw-was-here** [comment]
For YETUS-736?  I'm working under the assumption that github is more likely to be network-closer for more people.

**Comment by busbey** [comment]
> For YETUS-736? I'm working under the assumption that github is more likely to be network-closer for more people.

yeah for YETUS-736. that sounds like a reasonable assumption.

**Comment by aw-was-here** [comment]
Looks like we aren't getting updates from [Jenkins](https://builds.apache.org/view/S-Z/view/Yetus/job/yetus-github-multibranch/view/change-requests/job/PR-26/) posted here.  Also had to trigger it with a scan.  I'm guessing we need to bug INFRA to add in the webhook.

**Comment by aw-was-here** [comment]
So... I had to fix YETUS-739 in order to fix this one too. Yay?

**Comment by aw-was-here** [comment]
I've uploaded the patch to JIRA. Closing this pull request.

**Pull request closed without merging**
