### PR TITLE
YETUS-915 Update GitHub vote emojis for usability by color blind folks

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by busbey** [comment]
Can we just make them configurable so that projects can work out what's good for them?

**Comment by Apache9** [comment]
> Can we just make them configurable so that projects can work out what's good for them?

We could but we still need to provide default emojis?
As the statement is that it is for color blindness, I do not think there will be a project in ASF can say that 'I do not care about the color blindness'?  So the old ones are not suitable...

**Comment by busbey** [comment]
Oh! In that case please change the commit message and jira subject to something that indicates the purpose, e.g. "update GitHub vote emojis for usability by color blind folks."

**Comment by busbey** [comment]
No worries. Sorry we missed this during reviews for adding emoji votes in the first place.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-73/1/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |  31m 53s |  Docker failed to build yetus/yetus:e8f542b3.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/73 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-73/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
