### PR TITLE
YETUS-954. Re-instate github token support

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by aw-was-here** [comment]
(I *think* our Jenkins password is actually a token, so let's find out)

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/1/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m  7s |  Docker mode activated.  |
| -1 :x: |  yetus  |   0m  5s |  Unprocessed flag(s): --github-token  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/97 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/1/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/2/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  5s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  markdownlint  |   0m  1s |  There were no new markdownlint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/97 |
| Optional Tests | dupname asflicense markdownlint shellcheck shelldocs |
| uname | Linux 0f81dd9018c2 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 8b44644 |
| Max. process+thread count | 45 (vs. ulimit of 2000) |
| modules | C: . asf-site-src precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/3/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  markdownlint  |   0m  1s |  There were no new markdownlint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 21s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 13s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/97 |
| Optional Tests | dupname asflicense markdownlint shellcheck shelldocs |
| uname | Linux e7b001bcdd68 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 8b44644 |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: . asf-site-src precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-97/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
