### PR TITLE
YETUS-937. fix *Release Doc Maker* link

### PR DESCRIPTION
**Pull request by redsnow1992**

### CODE REVIEW

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m 15s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  markdownlint  |   0m  1s |  There were no new markdownlint issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 12s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-85/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/85 |
| Optional Tests | dupname asflicense markdownlint |
| uname | Linux 4350064d8ac8 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / b3a402b |
| Max. process+thread count | 41 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-85/1/console |
| versions | git=2.7.4 maven=3.3.9 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 45s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  markdownlint  |   0m  1s |  There were no new markdownlint issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 11s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-85/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/85 |
| Optional Tests | dupname asflicense markdownlint |
| uname | Linux 14ac977c1907 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 5b1fb16 |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-85/2/console |
| versions | git=2.7.4 maven=3.3.9 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by redsnow1992** [comment]
👌

**Comment by redsnow1992** [comment]
@busbey

**Comment by aajisaka** [comment]
Hi @redsnow1992 
This PR looks good to me. Would you create an issue for this PR?
JIRA URL: https://issues.apache.org/jira/projects/YETUS

**Comment by redsnow1992** [comment]
Hi @aajisaka  
jira: https://issues.apache.org/jira/browse/YETUS-937
Thx

**Pull request merged**
