### PR TITLE
[DO NOT MERGE] YETUS-957 + Maven 3.6.3 for testing

### PR DESCRIPTION
**Pull request by aajisaka**
This is a test for #99

### CODE REVIEW

**Comment by aajisaka** [comment]
Umm
```
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/bash -o pipefail -c apt-get -q update && apt-get -q install --no-install-recommends -y         perl         libperl-critic-perl     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-100/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  11m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 20s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 14s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  5s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  6s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  1s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 10s |  precommit in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |  14m 57s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-100/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/100 |
| Optional Tests | dupname asflicense shellcheck shelldocs javac javadoc unit hadolint |
| uname | Linux 7e249088d5aa 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 7996642 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-100/1/testReport/ |
| Max. process+thread count | 100 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-100/1/console |
| versions | git=2.7.4 maven=3.6.3 shellcheck=0.7.0 hadolint=1.17.5-0-g443423c |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
LGTM

**Comment by aajisaka** [comment]
Merged #99. Closing.

**Pull request closed without merging**
