### PR TITLE
YETUS-1019. Replace whitespace with blanks

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Review by busbey — COMMENTED** [review]
we should call out in the release note that the old whitespace cli option are deprecated and will get removed (unless we want to start having some kind of "you used a deprecated feature run with `--what-was-deprecated` for details" warning.)

also still flag it as incompatible because if folks were enabling or disabling the plugin via its name as whitespace that won't work now? or do we still want that to work?

**Comment by aw-was-here** [comment]
> we should call out in the release note that the old whitespace cli option are deprecated and will get removed (unless we want to start having some kind of "you used a deprecated feature run with `--what-was-deprecated` for details" warning.)

Good point. I'll add that to the release notes.

> also still flag it as incompatible because if folks were enabling or disabling the plugin via its name as whitespace that won't work now? or do we still want that to work?

Yup, I'll also add that to the release notes.  But yeah, as written the bw compat will only work for people who don't mention it by name (which AFAIK is the vast majority of people).

**Comment by aw-zededa** [comment]
Just so it's officially noted here, I've updated the release note in JIRA.

**Comment by aw-was-here** [comment]
Just so it is noted here, I've updated the release notes in JIRA.

**Review by busbey — APPROVED** [review]

**Comment by aw-was-here** [comment]
Thanks! I'll merge this in now...

**Pull request merged**
