### PR TITLE
YETUS-1006. Determine git sha

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by aajisaka** [comment]
The PR looks good to me.

https://github.com/apache/yetus/pull/141/checks?check_run_id=1183164907#step:3:661

> githubstatus-report: Failed to write status. Maybe the credential does not have write access to repo:status.

test-patch in the GitHub Action fails to add the commit status. I think this is because the GitHub Action does not set the credential and it is the expected behavior. Is my understanding correct?

**Comment by aajisaka** [comment]
Testing YETUS-1006: https://github.com/apache/hadoop/pull/2348

**Comment by aw-was-here** [comment]
> The PR looks good to me.
> 
> [#141 (checks)](https://github.com/apache/yetus/pull/141/checks?check_run_id=1183164907#step:3:661)
> 
> > githubstatus-report: Failed to write status. Maybe the credential does not have write access to repo:status.
> 
> test-patch in the GitHub Action fails to add the commit status. I think this is because the GitHub Action does not set the credential and it is the expected behavior. Is my understanding correct?

**Comment by aw-was-here** [comment]
> test-patch in the GitHub Action fails to add the commit status. I think this is because the GitHub Action does not set the credential and it is the expected behavior. Is my understanding correct?

https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

**Comment by aw-was-here** [comment]
Argh. I meant to commit this. Grr.

Thanks for the review.

**Pull request merged**
