### PR TITLE
YETUS-896 Use emoji as vote result on github

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/1/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m  0s |  Docker mode activated.  |
| :broken_heart: |  docker  |  13m 49s |  Docker failed to build yetus/yetus:de5900d.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/68 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/1/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/2/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m  0s |  Docker mode activated.  |
| :broken_heart: |  docker  |  13m 48s |  Docker failed to build yetus/yetus:de5900d.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/68 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/2/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/3/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m  9s |  Precommit patch detected.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 11s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| :green_heart: |  shellcheck  |   0m  2s |  There were no new shellcheck issues.  |
| :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   0m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/68 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux asf916.gq1.ygridcore.net 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/yetus-github-multibranch_PR-68/out/precommit/personality/provided.sh |
| git revision | master / 6b94d9d |
| modules | C: . precommit U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-68/3/console |
| versions | git=2.7.4 maven=2014-02-14T17:37:52+00:00) shellcheck=0.3.7 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Ping @busbey

**Comment by busbey** [comment]
@Apache9 and @infraio could y'all come to consensus between this as #67?

**Comment by infraio** [comment]
> @Apache9 and @infraio could y'all come to consensus between this as #67?

+1 for this. For me, the important thing is the “broken heart” emoji which if very helpful for us to find the -1 problem.

**Comment by Apache9** [comment]
Yes we just discussed offline. @infraio is fine with the approach here. So any other concerns? If no, let's include this and make a new yetus release?

Thanks. @busbey

**Pull request closed without merging**
