### PR TITLE
YETUS-737. perms are wrong on user_params.txt

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/2/console in case of problems.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/3/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 16 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 79 | master passed |
| +1 | javadoc | 10 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 9 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 7 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8 | precommit in the patch passed. |
| +1 | asflicense | 7 | The patch does not generate ASF License warnings. |
| | | 155 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  hadolint  shellcheck  |
| uname | Linux 654dfbd496e6 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3a14572 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/2/testReport/ |
| Max. process+thread count | 90 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/2/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 798 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 80 | master passed |
| +1 | javadoc | 10 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 9 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 2 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 8 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8 | precommit in the patch passed. |
| +1 | asflicense | 8 | The patch does not generate ASF License warnings. |
| | | 940 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  hadolint  shellcheck  shelldocs  |
| uname | Linux 104d51a8a908 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3a14572 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/3/testReport/ |
| Max. process+thread count | 100 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/3/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
👍

**Comment by aw-was-here** [comment]
It's not actually working though. :(

```
-rwxrwxrwx 1 jenkins root 1455 Jan  4 18:49 /testptch/user_params.txt
rm: cannot remove '/testptch/user_params.txt': Permission denied
```

So I guess I need to change the group too?

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/4/console in case of problems.

**Comment by busbey** [comment]
Is the docker mount ro?

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 21 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 77 | master passed |
| +1 | javadoc | 10 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 8 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | shellcheck | 2 | There were no new shellcheck issues. |
| +1 | shelldocs | 1 | There were no new shelldocs issues. |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | javadoc | 8 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7 | precommit in the patch passed. |
| +1 | asflicense | 8 | The patch does not generate ASF License warnings. |
| | | 161 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  hadolint  shellcheck  shelldocs  |
| uname | Linux 0d6a30bfb022 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3a14572 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/4/testReport/ |
| Max. process+thread count | 89 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/4/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
> Is the docker mount ro?

Nope. It's created in the docker build though. I wonder if I need to change the permissions on that dir?

**Comment by busbey** [comment]
Is /testptch writable by the user? It looks like it gets made by a mkdir -p in the dockerfile

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/5/console in case of problems.

**Comment by aw-was-here** [comment]
> Is /testptch writable by the user? It looks like it gets made by a mkdir -p in the dockerfile

It does.  I'm going to set the ownership of it and everything underneath it to the user.  There's not much reason not to that I can think of.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 15 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 82 | master passed |
| +1 | javadoc | 9 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 8 | the patch passed |
| +1 | hadolint | 1 | There were no new hadolint issues. |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 1 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 8 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7 | precommit in the patch passed. |
| +1 | asflicense | 8 | The patch does not generate ASF License warnings. |
| | | 160 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  hadolint  shellcheck  shelldocs  |
| uname | Linux fecf7a67c3cb 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3a14572 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/5/testReport/ |
| Max. process+thread count | 90 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/5/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
Hooray! That seems to have worked.  Now let me clean it up...

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/6/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 15 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 81 | master passed |
| +1 | javadoc | 10 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 9 | the patch passed |
| +1 | hadolint | 2 | There were no new hadolint issues. |
| +1 | shellcheck | 0 | There were no new shellcheck issues. |
| +1 | shelldocs | 2 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 8 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8 | precommit in the patch passed. |
| +1 | asflicense | 8 | The patch does not generate ASF License warnings. |
| | | 159 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  hadolint  shellcheck  shelldocs  |
| uname | Linux 54ce0cbc0986 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 3a14572 |
| maven | version: Apache Maven 3.3.9 |
| Default Java | 1.8.0_191 |
| shellcheck | v0.4.6 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/6/testReport/ |
| Max. process+thread count | 92 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/6/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 4 | https://github.com/apache/yetus/pull/38 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/38 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-38/7/console |
| Powered by | Apache Yetus 0.9.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
