### PR TITLE
YETUS-1065. Add support for codespell

### PR DESCRIPTION
**Pull request by aw-was-here**
Preliminary patch because I'm not sure the dev version of codespell used here is quite stable yet. Plus should probably have a way to update the dictionary automatically in the container.  That said, it's be very helpful in our own development. Soooo?

### CODE REVIEW

**Comment by aw-was-here** [comment]
rebase

**Comment by aw-was-here** [comment]
rebase; version update

**Comment by aw-was-here** [comment]
rebase + squash

**Comment by aw-was-here** [comment]
OK, added -x support after some playing around with another codebase that has some stuff that wasn't well handled by just `.codespellrc`

**Review by rvs — APPROVED** [review]
LGTM

**Comment by aw-was-here** [comment]
Thanks!

**Pull request merged**
