### PR TITLE
YETUS-941. Wrong URL in the checkstyle report.

### PR DESCRIPTION
**Pull request by aajisaka**
JIRA: https://issues.apache.org/jira/browse/YETUS-941

### CODE REVIEW

**Comment by smengcl** [comment]
Thanks [~aajisaka] for looking into this.

Actually I also spent some time on this and figured that the culprit should be the `logfile` passed to `module_status` is the full path (should probably just be file name). I was still trying to figure out how to test the change. I'm glad you get the patch ready ahead of me. :D

A question though, how do you usually test such change in Yetus? I looked at README and https://yetus.apache.org/contribute/. But there's no instruction on how to run Yetus locally to build and test hadoop trunk. e.g. Which set of commands should I use? Thanks!

-Siyao

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-90/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  2s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m  4s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-90/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/90 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 2cdec3dc9d96 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 7f1243a |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-90/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aajisaka** [comment]
Thanks @smengcl and @aw-was-here for your reviews.

> How do you usually test such change in Yetus?
 
I sometimes run test-patch.sh locally. Building instruction is written in the following doc, however, you don't need to build it.
https://yetus.apache.org/contribute/releases/#release-candidates

**Pull request merged**
