### PR TITLE
YETUS-888. update various web components

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by aw-was-here** [comment]
take out the svg changes (except for removing the extra space)

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 810 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for branch |
| +1 | mvninstall | 77 | master passed |
| +1 | compile | 152 | master passed |
| +1 | checkstyle | 77 | master passed |
| +1 | javadoc | 105 | master passed |
| 0 | spotbugs | 305 | Both FindBugs and SpotBugs are enabled, using SpotBugs. |
| 0 | spotbugs | 7 | branch/yetus-assemblies no spotbugs output file (spotbugsXml.xml) |
| 0 | spotbugs | 8 | branch/yetus-dist no spotbugs output file (spotbugsXml.xml) |
| 0 | spotbugs | 8 | branch/asf-site-src no spotbugs output file (spotbugsXml.xml) |
| 0 | spotbugs | 8 | branch/precommit no spotbugs output file (spotbugsXml.xml) |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 6 | Maven dependency ordering for patch |
| +1 | mvninstall | 215 | the patch passed |
| +1 | jshint | 6 | There were no new jshint issues. |
| +1 | compile | 152 | the patch passed |
| +1 | javac | 152 | the patch passed |
| -0 | checkstyle | 7 | audience-annotations-component/audience-annotations: The patch generated 3 new + 58 unchanged - 2 fixed = 61 total (was 60) |
| -0 | checkstyle | 6 | audience-annotations-component/audience-annotations-jdiff: The patch generated 1 new + 10 unchanged - 1 fixed = 11 total (was 11) |
| -0 | checkstyle | 7 | audience-annotations-component: The patch generated 4 new + 68 unchanged - 3 fixed = 72 total (was 71) |
| -0 | checkstyle | 8 | root: The patch generated 4 new + 68 unchanged - 3 fixed = 72 total (was 71) |
| +1 | hadolint | 3 | There were no new hadolint issues. |
| +1 | markdownlint | 3 | There were no new markdownlint issues. |
| +1 | rubocop | 5 | There were no new rubocop issues. |
| +1 | shellcheck | 4 | There were no new shellcheck issues. |
| +1 | shelldocs | 2 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 28 | The patch has no ill-formed XML file. |
| +1 | javadoc | 100 | the patch passed |
| 0 | spotbugs | 8 | yetus-assemblies has no data from spotbugs |
| 0 | spotbugs | 7 | precommit has no data from spotbugs |
| 0 | spotbugs | 8 | asf-site-src has no data from spotbugs |
| 0 | spotbugs | 8 | yetus-dist has no data from spotbugs |
||| _ Other Tests _ |
| +1 | unit | 8 | audience-annotations in the patch passed. |
| +1 | unit | 9 | yetus-minimaven-plugin in the patch passed. |
| +1 | unit | 7 | yetus-assemblies in the patch passed. |
| +1 | unit | 8 | audience-annotations-jdiff in the patch passed. |
| +1 | unit | 8 | audience-annotations-component in the patch passed. |
| +1 | unit | 8 | precommit in the patch passed. |
| +1 | unit | 27 | releasedocmaker in the patch passed. |
| +1 | unit | 8 | shelldocs in the patch passed. |
| +1 | unit | 7 | asf-site-src in the patch passed. |
| +1 | unit | 7 | yetus-dist in the patch passed. |
| +1 | unit | 15 | yetus-maven-plugin in the patch passed. |
| +1 | unit | 35 | root in the patch passed. |
| +1 | asflicense | 82 | The patch does not generate ASF License warnings. |
| | | 2713 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/60 |
| Optional Tests | dupname asflicense rubocop javac javadoc unit xml compile jshint markdownlint spotbugs findbugs checkstyle shellcheck shelldocs hadolint |
| uname | Linux b5e0aeeab566 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / cfdb402 |
| Default Java | 1.8.0_212 |
| checkstyle | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/artifact/out/diff-checkstyle-audience-annotations-component_audience-annotations.txt |
| checkstyle | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/artifact/out/diff-checkstyle-audience-annotations-component_audience-annotations-jdiff.txt |
| checkstyle | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/artifact/out/diff-checkstyle-audience-annotations-component.txt |
| checkstyle | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/testReport/ |
| Max. process+thread count | 54 (vs. ulimit of 2000) |
| modules | C: audience-annotations-component/audience-annotations yetus-minimaven-plugin yetus-assemblies audience-annotations-component/audience-annotations-jdiff audience-annotations-component precommit releasedocmaker shelldocs asf-site-src yetus-dist yetus-maven-plugin . U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-60/4/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 spotbugs=3.1.11 jshint=2.10.2 hadolint=1.16.2-0-g3b6f5a6 markdownlint=0.15.0 rubocop=0.67.2 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
Thanks! Committing.

**Pull request merged**
