### PR TITLE
YETUS-1155: Fix site:site treeset problem

### PR DESCRIPTION
**Pull request by omalley**
Fixes the first problem that was caused because the yetus options weren't comparable to the standard option objects. I changed the TreeSet to a HashSet, which does not require more than hashCode & equals.

### CODE REVIEW

**Comment by omalley** [comment]
This fixes the first problem, but another class cast exception remains.

**Comment by omalley** [comment]
Ugh, the javadoc api is really bad. It is downcasting from the interface in the parameter list (DocletEnvironment) to a specific class (DocEnvImpl) that is private inside of the javadoc jar. I'm not sure how we can fix that.

**Comment by aajisaka** [comment]
Thank you @omalley for the PR. I tried the same thing and faced the class cast exception.

**Review by aajisaka — APPROVED** [review]

**Comment by omalley** [comment]
The remaining problem is filed as a wont_fix bug on java. https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8203045

**Comment by aw-was-here** [comment]
I've started a DISCUSS thread on the mailing list.  I think we need to figure out what the long term plan should be with community input.  All of the options are pretty awful. 😦

**Comment by aw-was-here** [comment]
I'm going to go ahead and merge this but not close the JIRA since we still need to make a decision on what to do with the full functionality.

Thanks @omalley !

**Comment by aw-was-here** [comment]
Actually, I take that back. I am going to go ahead and close the JIRA. I didn't realize you put the internal impl in place. :dancers:

**Pull request merged**
