### PR TITLE
YETUS-943 Test patch fails to extract version information from a JDK11 jvm

### PR DESCRIPTION
**Pull request by ndimiduk**
Instead of parsing the output targeted at a human, let's parse the output targeted at a robot. Also include the vendor information rather than just the vendor-specific version string.

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 51s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  4s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/91 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux a095ff3fb451 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 46cb589 |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
>  versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0

So we'll pull out a maven version but not the underlying jdk version if we don't touch java files?

**Comment by aw-was-here** [comment]
Has MultiJDK mode been tested with these changes?  The returned string is used for file names and more ...

**Comment by aw-was-here** [comment]
> > versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0
> 
> So we'll pull out a maven version but not the underlying jdk version if we don't touch java files?

The versions reflect which plug-ins were called. Since the build tool is maven, the maven version is reported.

**Comment by ndimiduk** [comment]
> Has MultiJDK mode been tested with these changes? The returned string is used for file names and more ...

Yes I have it wired into this build, which I will be inspecting this morning. https://builds.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-1183/19/pipeline

**Comment by ndimiduk** [comment]
> > > versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0
> > 
> > 
> > So we'll pull out a maven version but not the underlying jdk version if we don't touch java files?
> 
> The versions reflect which plug-ins were called. Since the build tool is maven, the maven version is reported.

I've become "uncomfortable" with these reports when running in `--docker` mode; they report what's available on the host machine, not what's used within the environment.

**Comment by busbey** [comment]
versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0

> > >So we'll pull out a maven version but not the underlying jdk version if we don't touch java files?
> >
> > The versions reflect which plug-ins were called. Since the build tool is maven, the maven version is reported.
> > 
> I've become "uncomfortable" with these reports when running in --docker mode; they report what's available on the host machine, not what's used within the environment.

That sounds like a bug. It's supposed to be what's in the container. unless maybe we mount host JAVA_HOME when given?

**Comment by aw-was-here** [comment]
> > I've become "uncomfortable" with these reports when running in --docker mode; they report what's available on the host machine, not what's used within the environment.

VERSION_DATA, which stores most of this info, like most of the Yetus-specific globals are wiped clean and recalculated upon re-exec.  There is one version number that I can think of that is passed through as a special case, however:  the docker version.  There is no way to know that info reliably once precommit is on the other side of the container wall AFAIK. (Specifically here: https://github.com/apache/yetus/blob/46cb58913f05b0fa257d923681268c03ff504f84/precommit/src/main/shell/core.d/docker.sh#L819 )

> That sounds like a bug. It's supposed to be what's in the container. unless maybe we mount host JAVA_HOME when given?

The JAVA_HOME env var is, however, passed in ( https://github.com/apache/yetus/blob/46cb58913f05b0fa257d923681268c03ff504f84/precommit/src/main/shell/core.d/docker.sh#L37 ) . On re-exec, the java.sh logic kicks in to establish if the JAVA_HOME value is valid (https://github.com/apache/yetus/blob/46cb58913f05b0fa257d923681268c03ff504f84/precommit/src/main/shell/test-patch.d/java.sh#L51) .  In turn, this means if JAVA_HOME points to a valid path both inside and outside the container, it will get used. It is effectively used as a replacement for using --java-home.

Also, keep in mind this hack: https://github.com/apache/yetus/blob/46cb58913f05b0fa257d923681268c03ff504f84/precommit/src/main/shell/test-patch-docker/launch-test-patch.sh#L44 to make sure we have SOMETHING in JAVA_HOME if the user never set it at all and the project uses ant/gradle/maven/whatever.

Volume mounting binaries should absolutely not be happening, otherwise, OS X and Windows hosts running precommit would blow up spectacularly.

**Comment by ndimiduk** [comment]
> VERSION_DATA, which stores most of this info, like most of the Yetus-specific globals are wiped clean and recalculated upon re-exec. There is one version number that I can think of that is passed through as a special case, however: the docker version. There is no way to know that info reliably once precommit is on the other side of the container wall AFAIK. 

Maybe what I'm observing is a bug specific to maven then? IIRC, HBase docker runs provide their own maven (v3.5.x), while I regularly see reported maven versions at 3.0.x or 3.3.x, which I believe come from the host environment. Let me investigate this and return with an actual bug report if in fact there is a bug, instead of these anecdotal observations.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/2/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 54s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  6s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/91 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 3f816236c652 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 52ac7ff |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/3/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  6s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 54s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/91 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 490426191f2d 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 52ac7ff |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Looks like multijdk doesn't fully handle unit test results. It runs them, but the reports are not complete. Is that filed as a known issue?

**Comment by aw-was-here** [comment]
> Looks like multijdk doesn't fully handle unit test results. It runs them, but the reports are not complete. Is that filed as a known issue?

That's a regression if it's broken.  It definitely used to work.  Since I haven't really done Java stuff for a quite a while now (2 years?) I'm not sure if/when it broke.  There's a risk here that it might be patch related though: I'm fairly certain the jdk versions are sorted such that there is an assumption that the 'oldest' version will be first.  Putting names in will absolutely break that.  But that behavior should be verified.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/4/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  6s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 50s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/91 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 8f46c7fe2bfa 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0dc9e47 |
| Max. process+thread count | 41 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/4/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
@aw-was-here I'm not sure I know how to distinguish one from the other. When you have a moment, please take a look at the results on apache/hbase#1214. I'd like to get this one landed sooner than later, as we're very shortly needing to depend on multijdk OR write all of our jenkinsfiles to manage multiple invocations of Yetus. Thanks.

**Comment by ndimiduk** [comment]
Looks like unit results by JDK are not being recorded properly in the table details, but failures are reported by JDK in the summary post-matter.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/5/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  5s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  1s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m  0s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/91 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 1c54adc7dbc0 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 79eadbd |
| Max. process+thread count | 51 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-91/5/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Thanks for looking @aw-was-here . I gave it another pass, updated it to use `grep` and `awk` from the variables rather than system path.

**Comment by ndimiduk** [comment]
Okay, Yetus precommit checks pass (nice, btw!).

I kicked the PR on apache/hbase#1214, which will grab this latest change, make sure no surprises slipped in.

**Pull request merged**
