### PR TITLE
YETUS-914. 'make test' is not processed correctly

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-75/1/console in case of problems.

**Comment by apache-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |  31m  7s |  Docker failed to build yetus/yetus:e8f542b3.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/yetus/pull/75 |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-75/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-75/2/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  30m  2s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  shelldocs  |   0m  0s |  There were no new shelldocs issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   |  30m 33s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-75/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/75 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 212a0e438a34 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / b067f8e |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-75/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
Thanks for the review!

**Pull request merged**
