### PR TITLE
YETUS-858. Add support for Golang

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 391 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 87 | master passed |
| +1 | javadoc | 20 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 5 | Maven dependency ordering for patch |
| +1 | mvninstall | 17 | the patch passed |
| +1 | hadolint | 4 | There were no new hadolint issues. |
| +1 | markdownlint | 1 | There were no new markdownlint issues. |
| +1 | shellcheck | 7 | There were no new shellcheck issues. |
| +1 | shelldocs | 3 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 15 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8 | precommit in the patch passed. |
| +1 | unit | 5 | asf-site-src in the patch passed. |
| +1 | asflicense | 14 | The patch does not generate ASF License warnings. |
| | | 620 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/57 |
| Optional Tests | dupname asflicense markdownlint shellcheck shelldocs javac javadoc unit hadolint |
| uname | Linux bdb353951315 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / a3800fb |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/1/testReport/ |
| Max. process+thread count | 89 (vs. ulimit of 2000) |
| modules | C: precommit asf-site-src U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 hadolint=1.16.2-0-g3b6f5a6 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/2/console in case of problems.

**Comment by aw-was-here** [comment]
Redid the Dockerfile a bit to hardset golangci-lint and to make it a bit more cache-able.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 544 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| 0 | mvndep | 11 | Maven dependency ordering for branch |
| +1 | mvninstall | 83 | master passed |
| +1 | javadoc | 18 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 3 | Maven dependency ordering for patch |
| +1 | mvninstall | 15 | the patch passed |
| +1 | hadolint | 3 | There were no new hadolint issues. |
| +1 | markdownlint | 1 | There were no new markdownlint issues. |
| +1 | shellcheck | 8 | There were no new shellcheck issues. |
| +1 | shelldocs | 2 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 13 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7 | precommit in the patch passed. |
| +1 | unit | 6 | asf-site-src in the patch passed. |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 756 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/57 |
| Optional Tests | dupname asflicense markdownlint shellcheck shelldocs javac javadoc unit hadolint |
| uname | Linux 0058c2c1d7e5 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / a3800fb |
| Default Java | 1.8.0_212 |
|  Test Results | https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/2/testReport/ |
| Max. process+thread count | 90 (vs. ulimit of 2000) |
| modules | C: precommit asf-site-src U: . |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-57/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 hadolint=1.16.2-0-g3b6f5a6 markdownlint=0.15.0 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by rvs** [comment]
LGTM (in all the places where I can actually provide meaningful feedback ;-))

**Comment by aw-was-here** [comment]
Thanks!

**Pull request merged**
