### PR TITLE
YETUS-860. mvn dependency order needs special handling for version ch…

### PR DESCRIPTION
**Pull request by aw-was-here**
…ange

### CODE REVIEW

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/1/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 120 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 1 | There were no new shellcheck issues. |
| +1 | shelldocs | 1 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 9 | The patch does not generate ASF License warnings. |
| | | 148 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/55 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux ef730bc05483 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0478292 |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Comment by aw-was-here** [comment]
There's some optimizations that need to happen here yet, now that I look at this a bit closer.

**Comment by apache-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/2/console in case of problems.

**Comment by apache-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 102 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 | shellcheck | 2 | There were no new shellcheck issues. |
| +1 | shelldocs | 0 | There were no new shelldocs issues. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
||| _ Other Tests _ |
| +1 | asflicense | 9 | The patch does not generate ASF License warnings. |
| | | 145 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/yetus/pull/55 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 50a1661fb029 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | precommit/src/main/shell/personality/yetus.sh |
| git revision | master / 0478292 |
| Max. process+thread count | 46 (vs. ulimit of 2000) |
| modules | C: precommit U: precommit |
| Console output | https://builds.apache.org/job/yetus-github-multibranch/job/PR-55/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.6.0 |
| Powered by | Apache Yetus 0.11.0-SNAPSHOT http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
